### PR TITLE
Update build.rs to use CMake to build, and update libui to latest

### PR DESCRIPTION
**Pull request by ghost**
This also includes the fix in build.rs to find the .dylib on Mac (pcwalton/libui-rs#1), but sadly the examples aren't working.

### CODE REVIEW

**Comment by talklittle** [comment]
Tested and works for me on OSX

**Comment by mitchhentges** [comment]
> but sadly the examples aren't working.

Hmm, maybe it's just that they're not being built by default. I just did a `cargo run controlgallery` and it's rippin' here on Linux:

2016-07-18-204801_642x507

**Comment by talklittle** [comment]
@mitchhentges The controlgallery example should crash after updating the upstream libui, since the API becomes out of sync. #3 fixes this crash.

Were you testing on libui-rs `master` branch? If so then you wouldn't experience the crash, since you didn't update the upstream libui submodule.

**Comment by mitchhentges** [comment]
I'm definitely on Machtan's branch:

```
$ git log
commit 032aa2b71703a9dc69ae8f5b715840de58f49caa
Author: Jakob Lautrup Nysom <jako3047@gmail.com>
Date:   Sun Jun 5 14:01:55 2016 +0200

    Only rerun build.rs if libui is updated
```

**Comment by talklittle** [comment]
@mitchhentges `git submodule update` after you checked out `Machtan/master`?

**Comment by mitchhentges** [comment]
@talklittle I cloned directly from Machtan

**Comment by talklittle** [comment]
@mitchhentges Ok, it must have to do with the differences between Linux and OSX. On OSX the Machtan branch crashes, while pcwalton is fine, and also fine after applying #3 (verified just now).

I guess the memory layout of Combobox and EditableCombobox are similar enough to avoid crashes on Gtk and Linux.

**Pull request closed without merging**
